spring:
  application:
    name: example-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.20.18.160:3306/unify_zjzb_bl?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: cprs_broker
    password: cprs_broker

mybatis-plus:
  check-config-location: true
  mapper-locations: classpath*:/mysql/mapper/*.xml
  type-aliases-package: com.bobofans.business.trip.*.entity
