spring:
  application:
    name: example-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.20.18.160:3306/unify_zjzb_bl?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: cprs_broker
    password: cprs_broker

logging:
  log4j2:
    config:
      override: classpath:log4j2.xml

mybatis-plus:
  check-config-location: true
  mapper-locations: classpath*:/mysql/mapper/*.xml
  type-aliases-package: com.bobofans.business.trip.*.entity

decorator:
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: com.bobofans.business.trip.common.mybatis.StdLog4jLogger
